export const dataStore = {
  courses: [
    { id: 1, name: "Frontend ReactJS", duration: "6 oy", price: 850000 },
    { id: 2, name: "Python Backend (Django)", duration: "6 oy", price: 900000 },
    { id: 3, name: "General English (IELTS)", duration: "8 oy", price: 750000 },
    { id: 4, name: "Grafik Dizayn & UI/UX", duration: "4 oy", price: 800000 },
    {
      id: 5,
      name: "Flutter Mobile Development",
      duration: "6 oy",
      price: 950000,
    },
    {
      id: 6,
      name: "Cybersecurity & Pentesting",
      duration: "5 oy",
      price: 1100000,
    },
  ],
  groups: [
    {
      id: "G-101",
      courseId: 1,
      courseName: "Frontend ReactJS",
      name: "F-12 Guruh",
      teacherId: 101,
      teacherName: "Abdulaziz Abdulhayev",
      room: "201-xona (Kompyuter zali)",
      scheduleDays: "Dushanba - Chorshanba - Juma",
      scheduleTime: "14:00 - 16:00",
      monthlyFee: 850000,
      status: "Active",
      startDate: "2026-02-01",
    },
    {
      id: "G-102",
      courseId: 2,
      courseName: "Python Backend (Django)",
      name: "P-04 Guruh",
      teacherId: 103,
      teacherName: "Azizbek Murodov",
      room: "203-xona (Backend Lab)",
      scheduleDays: "Seshanba - Payshanba - Shanba",
      scheduleTime: "16:30 - 18:30",
      monthlyFee: 900000,
      status: "Active",
      startDate: "2026-03-01",
    },
    {
      id: "G-103",
      courseId: 3,
      courseName: "General English (IELTS)",
      name: "E-09 Guruh",
      teacherId: 110,
      teacherName: "Farhod Saidov",
      room: "102-xona (Media xona)",
      scheduleDays: "Dushanba - Chorshanba - Juma",
      scheduleTime: "10:00 - 12:00",
      monthlyFee: 750000,
      status: "Active",
      startDate: "2026-01-15",
    },
  ],
  students: [
    {
      id: 1,
      fullName: "Abdulaziz Abdulhayev",
      phone: "+998 90 599 06 00",
      parentPhone: "+998 90 599 06 00",
      groupId: "G-101",
      groupName: "F-12 Guruh (ReactJS)",
      joinDate: "2026-02-01",
      paymentStatus: "Paid",
      balance: 0,
      status: "Active",
    },
    {
      id: 2,
      fullName: "Abdulaziz Abdulhayev (2)",
      phone: "+998 90 599 06 00",
      parentPhone: "+998 90 599 06 00",
      groupId: "G-101",
      groupName: "F-12 Guruh (ReactJS)",
      joinDate: "2026-02-01",
      paymentStatus: "Overdue",
      balance: -850000,
      status: "Active",
    },
    {
      id: 3,
      fullName: "Diyorbek Toshmatov",
      phone: "+998 90 599 06 00",
      parentPhone: "+998 90 599 06 00",
      groupId: "G-102",
      groupName: "P-04 Guruh (Python)",
      joinDate: "2026-03-01",
      paymentStatus: "Paid",
      balance: 0,
      status: "Active",
    },
  ],
  attendance: [
    {
      id: 501,
      groupId: "G-101",
      studentId: 1,
      date: "2026-08-10",
      status: "Present",
      note: "",
      reasonCategory: "",
    },
    {
      id: 502,
      groupId: "G-101",
      studentId: 2,
      date: "2026-08-10",
      status: "Absent",
      note: "Kasal",
      reasonCategory: "medical",
    },
    {
      id: 503,
      groupId: "G-102",
      studentId: 3,
      date: "2026-08-11",
      status: "Present",
      note: "",
      reasonCategory: "",
    },
  ],
  payments: [
    {
      id: "PAY-1001",
      studentId: 1,
      studentName: "Abdulaziz Abdulhayev",
      groupName: "F-12 Guruh (ReactJS)",
      amount: 850000,
      month: "Avgust 2026",
      paymentMethod: "Card (Click)",
      date: "2026-08-02",
      recordedBy: "Admin",
    },
    {
      id: "PAY-1002",
      studentId: 3,
      studentName: "Diyorbek Toshmatov",
      groupName: "P-04 Guruh (Python)",
      amount: 900000,
      month: "Avgust 2026",
      paymentMethod: "Naqd pul",
      date: "2026-08-05",
      recordedBy: "Admin",
    },
  ],
  teachers: [
    {
      id: 101,
      name: "Abdulaziz Abdulhayev",
      phone: "+998 90 599 06 00",
      subject: "Frontend ReactJS",
      salary: 12000000,
      experience: "5 yil",
      avatar: "👨‍💻",
    },
    {
      id: 102,
      name: "Sardor Rahimov",
      phone: "+998 90 599 06 00",
      subject: "Frontend Mentori",
      salary: 9000000,
      experience: "3 yil",
      avatar: "💻",
    },
    {
      id: 103,
      name: "Azizbek Murodov",
      phone: "+998 90 599 06 00",
      subject: "Python Backend",
      salary: 11000000,
      experience: "4 yil",
      avatar: "🐍",
    },
  ],
  exams: [
    {
      id: "EX-101",
      groupName: "F-12 Guruh (ReactJS)",
      title: "React State & Hooks Oraliq Imtihon",
      date: "2026-08-15",
      totalScore: 100,
      maxPassingScore: 70,
      status: "Upcoming",
    },
    {
      id: "EX-102",
      groupName: "P-04 Guruh (Python)",
      title: "Django REST API Yakuniy Imtihon",
      date: "2026-08-10",
      totalScore: 100,
      maxPassingScore: 75,
      status: "Completed",
    },
  ],
  homework: [
    {
      id: "HW-1",
      groupName: "F-12 Guruh (ReactJS)",
      title: "Custom Hooks & Redux Toolkit App",
      deadline: "2026-08-16",
      totalSubmitted: 12,
      status: "Active",
    },
    {
      id: "HW-2",
      groupName: "P-04 Guruh (Python)",
      title: "PostgreSQL Database Schema & ORM Model",
      deadline: "2026-08-14",
      totalSubmitted: 8,
      status: "Active",
    },
  ],
  certificates: [
    {
      id: "CERT-8801",
      studentName: "Abdulaziz Abdulhayev",
      courseName: "Frontend ReactJS",
      issueDate: "2026-08-01",
      qrCode: "QR-8801-VERIFIED",
      grade: "A+ (98%)",
    },
    {
      id: "CERT-8802",
      studentName: "Rayhona Sobirova",
      courseName: "Grafik Dizayn & UI/UX",
      issueDate: "2026-07-28",
      qrCode: "QR-8802-VERIFIED",
      grade: "A (92%)",
    },
  ],
  rooms: [
    {
      id: "R-201",
      name: "201-xona (Kompyuter Zali)",
      capacity: 20,
      computersCount: 20,
      projector: "Mavjud",
      status: "Active",
    },
    {
      id: "R-202",
      name: "202-xona (Dizayn Lab)",
      capacity: 16,
      computersCount: 16,
      projector: "Mavjud",
      status: "Active",
    },
  ],
  leads: [
    {
      id: "L-501",
      name: "Jasurbek Rustamov",
      phone: "+998 90 599 06 00",
      interestedCourse: "Frontend ReactJS",
      source: "Instagram Ads",
      status: "Yangi",
    },
    {
      id: "L-502",
      name: "Dildora Alimova",
      phone: "+998 90 599 06 00",
      interestedCourse: "General English",
      source: "Telegram Bot",
      status: "Qo'ng'iroq qilindi",
    },
  ],
};
